"""Household-style prompts added for workstream D (hibrid48 draft head): chat, prose and advice, the kinds where the
checkpoint's own MTP head drafts worst (about 2.1 tokens a round on prose). Written for this item; none is a decode
suite prompt (tf_decode_sampled.py), which stay held out. Replies are stored as tokens and text, never executed."""

from __future__ import annotations

from prompts_v1 import EXCLUDED, SYSTEMS

HCHAT = [
    "My in-laws are staying with us for a week. How do I keep everyone happy without wearing myself out?",
    "What can I make for dinner tonight with chicken thighs, rice, a lemon and some spinach?",
    "Our neighbourhood wants to start a book club. How should we run the first meeting?",
    "I have a free Saturday and a small budget. Suggest a nice day out for two adults.",
    "My teenage son wants a later curfew. How should we talk about it?",
    "Suggest a menu for a summer barbecue for twelve people, including something for kids.",
    "We're redecorating our bedroom. Give me some calm colour schemes and why they work.",
    "How do I plan a surprise anniversary dinner at home?",
    "My friend just had a baby. What are useful things I can do or bring?",
    "What's a good weekend routine to keep the house tidy without spending all Sunday cleaning?",
    "Can you help me plan a week of packed lunches for school that the kids will actually eat?",
    "We're going to visit my grandparents' home town. What should we ask them about before we go?",
    "Give me ideas for a family game night with a mix of ages from 5 to 70.",
    "I keep forgetting birthdays. How can I set up a simple system to remember them?",
    "Suggest a cozy Sunday for a couple who both work long hours during the week.",
    "My daughter wants a pet. How do we decide between a hamster, a rabbit and a cat?",
    "We're having a garage sale next weekend. How do we price things and set it up?",
    "What should I cook for a friend who's just come home from the hospital?",
    "Plan a simple afternoon tea party for my mum's 70th birthday.",
    "I want to start walking every morning before work. How do I make it stick?",
    "Our family keeps arguing about screen time. Help us write some fair house rules.",
    "Suggest some easy crafts I can do with a four-year-old using things around the house.",
    "What's a fun way to celebrate the first day of spring with the kids?",
    "Help me plan a relaxed Christmas Eve with friends who don't know each other well.",
    "I'm hosting a brunch for six on Sunday. What should I make that can be prepared the night before?",
    "What are some good conversation starters for a dinner party with new neighbours?",
    "We just bought our first house. What maintenance should we do in the first year?",
    "Help me plan a small backyard wedding reception for forty guests.",
    "What should we bring for a day at the lake with three kids under ten?",
    "Suggest a gentle weekly exercise plan for my dad who is 68 and just retired.",
    "My roommate never does the dishes. How do I bring it up without a fight?",
    "Our dog is getting old and slower. How can we make her more comfortable at home?",
    "Plan a rainy-day indoor treasure hunt for my niece and nephew.",
    "I want to cook more at home instead of ordering takeaway. Where do I start?",
    "What are some nice traditions we could start as a new family?",
    "Suggest a two-day itinerary for visiting a seaside town in the off season.",
    "My grandmother is lonely since grandpa passed. How can our family help her feel connected?",
    "We have a small balcony. How can we make it a nice place to sit in the evenings?",
    "What should I put in a care package for a college student during exams?",
    "Help me organise my kitchen cupboards so I can actually find things.",
    "Suggest a menu for a cosy winter dinner with soup and fresh bread.",
    "My sister and I want to plan a trip together for our mum. Where do we start?",
    "Give me a simple plan to declutter my wardrobe this weekend.",
    "We're throwing a Halloween party for eight-year-olds. What games and food should we have?",
    "How can I make our home feel more welcoming for guests who stay overnight?",
    "What's a good way to teach my kids about saving pocket money?",
    "I'm cooking for someone who is gluten free for the first time. What should I watch out for?",
    "Suggest ideas for a low-key New Year's Eve at home with a few friends.",
    "How do we divide up the holidays fairly between two sets of grandparents?",
    "Our street is organising a summer party. Suggest activities that bring neighbours together.",
    "I want to make a photo album of our family's year. How should I organise it?",
    "What are some easy weeknight dinners that use one pan?",
    "Help me write a short message to invite the new family next door for coffee.",
    "My kids fight in the car on every long drive. Any ideas?",
    "Plan a relaxed day at home for when I'm recovering from a cold.",
    "What should we consider when choosing a school for our daughter?",
    "Suggest a picnic in the park for a first date that isn't too fancy.",
    "How can I help my son get ready for his first sleepover?",
    "What are some ways to celebrate a friend's promotion without spending much?",
    "Give me a simple bedtime routine for a five-year-old who stalls every night.",
]

HCHAT += ['What are some fun, cheap date ideas for a couple with a new baby at home?', "Help me plan a relaxed Mother's Day breakfast in bed.", "We're visiting a big city with two kids for a weekend. How should we pace the days?", "What should I say in a toast at my parents' 40th anniversary dinner?", 'Our family wants one screen-free evening a week. What could we do instead?', "How do I host a games night for adults who don't know each other?", 'Suggest a simple weekly routine for watering and caring for a few balcony plants.',
    'My son is starting secondary school next month. How can we prepare him?', "What are good snacks to bring to a kids' football match for the whole team?", 'Plan a gentle day out for my grandmother who uses a walker.',
    'I want to surprise my wife with a homemade dinner. What should I cook if I rarely cook?',
    'What should we think about before getting a second car?',
    'Give me ideas for a cosy autumn weekend at home.',
    'Help me plan a baby shower for a friend on a small budget.',
    'Our kitchen is always cluttered. How can we keep the counters clear?', "What are good traditions for a family's first Christmas in a new house?", "I'm going to be home alone for a week. Suggest a plan so I don't get bored.", 'My neighbour just lost her husband. How can I help without intruding?',
    'Suggest five dinners I can make from one roast chicken.',
    'How should we plan a long weekend camping trip with a dog?', "What's a good way to welcome a new family to our street?", "Help me plan a children's sleepover for four nine-year-olds.", 'Suggest a simple morning routine for a family that is always late for school.',
    'What should we do on a rainy day at the beach house?',
    'Plan an outdoor movie night in the backyard for neighbours.',
    'We want to start eating breakfast together as a family. Any tips?',
    'Suggest some cheap ways to make our rented flat feel like home.',
    'My teenage daughter wants to redecorate her room. How do we set a budget together?',
    'What can we do to make long car journeys more fun for the kids?', "Plan a small garden party for my dad's 75th birthday."]

HPROSE = [
    "Write a short story about a family who finds an old recipe book in their new kitchen.",
    "Write a bedtime story about a little owl who is too curious to sleep.",
    "Write a warm short story about a grandfather and granddaughter building a birdhouse.",
    "Describe a busy family kitchen on a Sunday morning, in vivid detail.",
    "Write a short story about a lost teddy bear trying to get back to its owner.",
    "Write a letter from a mother to her son on the day he leaves for university.",
    "Write a short story about a postman who knows everyone's secrets but keeps them all.",
    "Write a cheerful story about a town that holds a festival for the first snowfall.",
    "Write a short story about a girl who plants a seed that grows overnight into something strange.",
    "Describe the first warm day of spring in a city park.",
    "Write a funny story about a family trying to assemble flat-pack furniture.",
    "Write a story about an old man who feeds the pigeons every morning and the day he doesn't come.",
    "Write a short story about a boy who trades his lunch for a mysterious map.",
    "Write a gentle story about a cat who adopts a family instead of the other way round.",
    "Write a short story about a baker who leaves one loaf every night for a stranger.",
    "Write a story about two sisters who haven't spoken in years meeting at a wedding.",
    "Write a children's story about a snail who wants to win a race.",
    "Write a short story set on a rainy afternoon in a small bookshop.",
    "Write a heartwarming story about a neighbour who fixes everyone's broken things.",
    "Describe a family road trip through the countryside from the point of view of the youngest child.",
    "Write a short story about a lonely robot vacuum cleaner.",
    "Write a story about a village that wakes up to find all its clocks have stopped.",
    "Write a short story about a girl who finds a note hidden in a library book.",
    "Write a story about a dog who waits at the train station every evening.",
    "Write a short story about the night the power went out on the whole street.",
    "Describe an old farmhouse kitchen at harvest time.",
    "Write a fairy tale about a king who can only speak in rhymes.",
    "Write a short story about a man who grows the biggest pumpkin in the county.",
    "Write a story about a grandmother's garden told through the seasons.",
    "Write a short story about a child's first day at the seaside.",
    "Write a story about a girl who builds a boat from things she finds on the beach.",
    "Write a short, funny story about a parrot who repeats the wrong things at dinner.",
    "Write a short story about a lost glove that travels around the city.",
    "Describe a snowy evening in a small mountain village, with lights coming on one by one.",
    "Write a story about a school caretaker who secretly helps the students.",
    "Write a bedtime story about the moon getting lost and the stars helping it home.",
    "Write a short story about a father learning to braid his daughter's hair.",
    "Write a story about an ice cream van that only appears on the hottest day of the year.",
    "Write a short story about a woman who opens a tiny museum in her front room.",
    "Write a story from the point of view of a family's old kitchen table.",
    "Write a short story about a boy who is afraid of swimming and the summer he learns.",
    "Write a cozy story about a snowed-in family playing board games by candlelight.",
    "Write a short story about a travelling circus arriving in a sleepy town.",
    "Write a letter from a grandmother to her grandchild who has just been born.",
    "Write a story about a stray kitten that turns up on a family's doorstep during a storm.",
    "Write a short story about a gardener who talks to her plants and one day they answer.",
    "Write a story about a family who swaps houses with strangers for a summer.",
    "Write a short story about a bus driver who knows every passenger's name.",
    "Describe a crowded Saturday market in a small town, full of sounds and smells.",
    "Write a short story about a child who writes letters to the tooth fairy and gets answers.",
    "Write a story about an old piano that plays by itself at night.",
    "Write a short story about two old friends who meet every year on the same bench.",
    "Write a story about a family's first holiday abroad and everything that surprised them.",
    "Write a short fable about a greedy squirrel and a generous crow.",
    "Write a story about a lighthearted competition between two neighbours' Christmas lights.",
    "Write a short story about a girl who learns to bake bread with her grandfather.",
    "Write a short story about a family moving to a farm and their first night there.",
    "Write a gentle story about an elderly couple dancing in their kitchen.",
    "Write a short story about a boy and a stray dog who become best friends.",
    "Write a story about a snowman who wants to see the summer.",
]

HPROSE += ['Write a short story about a family of hedgehogs preparing for winter.',
    'Write a warm story about a grandmother teaching her grandson to knit.',
    'Write a bedtime story about a cloud who wants to be a rainbow.',
    'Write a short story about a girl who keeps a diary for her future self.',
    'Write a story about a village baker who wins a contest with a forgotten recipe.',
    'Describe a family Sunday lunch at a long table in the garden.',
    'Write a short story about an old dog teaching a puppy the rules of the house.', "Write a story about a lost kite that lands in a stranger's garden.", "Write a short story about a child's first snow day.", 'Write a story about a family who finds a message in a bottle on holiday.',
    'Write a bedtime story about a small train that is afraid of tunnels.',
    'Write a short story about a neighbour who plays the violin every evening.',
    'Write a story about two brothers building a treehouse one summer.',
    'Describe a cosy café on a rainy afternoon, full of small details.',
    'Write a short story about a girl who rescues a baby bird.', "Write a story about a grandfather's old bicycle and the places it has been.", 'Write a short story about a family of mice living in a bookshop.',
    'Write a story about the day the whole town lost power and gathered in the square.', "Write a short story about a boy who learns to bake his mother's birthday cake.", 'Write a story about a little boat that sails from a river to the sea.',
    'Write a short story about a cat who visits a different house every night.',
    'Write a gentle story about moving away from a childhood home.', "Write a short story about a girl and her grandmother's garden gnome.", 'Write a story about a family who adopts an old, grumpy tortoise.',
    'Write a bedtime story about the sun and the moon swapping places for a day.',
    'Write a short story about a school play where everything goes wrong.',
    'Write a story about a lonely scarecrow who makes friends with the crows.',
    'Write a short story about a postcard that arrives fifty years late.',
    'Write a story about a family recipe passed down through four generations.',
    'Write a short story about a dog who learns to open the fridge.']

HADVICE = [
    "How do I get red wine out of a light-coloured carpet?",
    "What's the best way to store fresh herbs so they last longer?",
    "How do I choose a good mattress without spending a fortune?",
    "How often should I really clean the different parts of my house?",
    "What's a simple way to start budgeting as a family?",
    "How do I help my child with maths homework when I'm not good at maths myself?",
    "How can I make my houseplants survive while I'm away for two weeks?",
    "What should I look for when buying a used family car?",
    "How can I reduce our electricity bill in winter?",
    "How do I teach my kid to ride a bike without training wheels?",
    "What are good ways to keep a small kitchen organised?",
    "How do I get my picky eater to try new vegetables?",
    "How do I prepare my garden for winter?",
    "What's the easiest way to keep track of family appointments and activities?",
    "How can I sleep better when I'm stressed about work?",
    "How should I introduce a new cat to our old dog?",
    "What's a good way to prepare for a job interview after years at home with the kids?",
    "How do I remove mould from the bathroom ceiling safely?",
    "How can I make meal planning less of a chore?",
    "What are good first chores for a three-year-old?",
    "How do I talk to my elderly parents about moving somewhere smaller?",
    "What's the best way to pack fragile things for a house move?",
    "How do I make a cheap and cheerful kids' bedroom makeover?",
    "How should we prepare the house before bringing a new baby home?",
    "How do I keep my fridge from getting smelly?",
    "What's a good routine for looking after a lawn in summer?",
    "How do I help my teenager manage exam stress?",
    "How can I host Christmas dinner without spending the whole day in the kitchen?",
    "How do I deal with a noisy upstairs neighbour politely?",
    "What should be in a basic first-aid kit at home?",
]

# short household dialogs: the model answers the last user turn
HDIALOGS = [
    [{"role": "user", "content": "I want to bake something with the kids this afternoon."},
     {"role": "assistant", "content": "Lovely idea! How old are the kids, and do you have any ingredients you'd like "
                                      "to use up?"},
     {"role": "user", "content": "They're 6 and 9, and we have bananas, flour, eggs and some chocolate chips."}],
    [{"role": "user", "content": "Can you help me plan my week? I have too much going on."},
     {"role": "assistant", "content": "Of course. What are the fixed things this week, like work hours, school runs "
                                      "or appointments?"},
     {"role": "user", "content": "Work 9 to 5 Monday to Friday, the dentist on Wednesday at 4, football practice "
                                 "for my son on Tuesday and Thursday at 6, and I want to fit in two workouts."}],
    [{"role": "user", "content": "We're thinking of getting a dog."},
     {"role": "assistant", "content": "That's exciting! Tell me a bit about your home and routine, and I can help "
                                      "you think about which kind of dog would fit."},
     {"role": "user", "content": "Small flat, no garden, we both work but one of us is home three days a week."}],
    [{"role": "user", "content": "My mum's birthday is next week and I have no idea what to get her."},
     {"role": "assistant", "content": "Let's figure it out. What does she enjoy doing in her free time?"},
     {"role": "user", "content": "She loves gardening, reading mysteries and doing crosswords with her tea."}],
    [{"role": "user", "content": "I want to write a story for my daughter's bedtime."},
     {"role": "assistant", "content": "What a nice idea. What does she love right now? Animals, space, princesses, "
                                      "something else?"},
     {"role": "user", "content": "She's obsessed with otters and she's scared of thunderstorms."}],
    [{"role": "user", "content": "What should I cook for dinner tonight?"},
     {"role": "assistant", "content": "Happy to help! What do you have in the fridge, and how much time do you have?"},
     {"role": "user", "content": "About 30 minutes. Eggs, half a bag of potatoes, an onion, some cheese and frozen "
                                 "peas."}],
    [{"role": "user", "content": "Our living room always looks messy."},
     {"role": "assistant", "content": "That's really common. What tends to pile up there the most?"},
     {"role": "user", "content": "Toys, mail, shoes, and blankets from the sofa."}],
    [{"role": "user", "content": "I'm planning a camping weekend with friends."},
     {"role": "assistant", "content": "Sounds fun! How many people, and will you be at a campsite with facilities "
                                      "or somewhere more remote?"},
     {"role": "user", "content": "Six of us, at a campsite with toilets and showers but no shop. Two nights."}],
    [{"role": "user", "content": "Can you write a short poem for my husband's retirement card?"},
     {"role": "assistant", "content": "I'd love to. What did he do for work, and what is he looking forward to?"},
     {"role": "user", "content": "He was a train driver for 35 years, and he wants to fish and see more of the "
                                 "grandkids."}],
    [{"role": "user", "content": "My kids are bored in the summer holidays already."},
     {"role": "assistant", "content": "It's only the first week! How old are they, and what do they usually enjoy?"},
     {"role": "user", "content": "8 and 11. They like building things, being outside, and anything with animals."}],
    [{"role": "user", "content": "Help me write a message to my book club."},
     {"role": "assistant", "content": "Sure. What do you need to tell them?"},
     {"role": "user", "content": "The next meeting moves from Thursday to Friday at my place, and we're reading a "
                                 "new book because nobody could find copies of the old one."}],
    [{"role": "user", "content": "I want to start a small vegetable patch on my balcony."},
     {"role": "assistant", "content": "Great project. Which way does the balcony face, and roughly how big is it?"},
     {"role": "user", "content": "South facing, about two metres by one, and it gets windy."}],
    [{"role": "user", "content": "We're having friends over and one of them is vegan."},
     {"role": "assistant", "content": "No problem. Is it a full dinner, or snacks and drinks?"},
     {"role": "user", "content": "A full dinner for six, and I'd like one main dish everyone can eat."}],
    [{"role": "user", "content": "Tell me a story."},
     {"role": "assistant", "content": "Happily! Any preferences? Funny, cozy, adventurous, spooky?"},
     {"role": "user", "content": "Cozy, with a cat and a bakery, please."}],
    [{"role": "user", "content": "I need to plan my son's 10th birthday."},
     {"role": "assistant", "content": "Fun! Do you want a party at home or somewhere else, and roughly how many "
                                      "kids?"},
     {"role": "user", "content": "At home, about ten kids, and he's really into football and science experiments."}],
    [{"role": "user", "content": "I've been feeling really tired lately and my evenings are chaotic."},
     {"role": "assistant", "content": "I'm sorry to hear that. What does a typical evening look like for you right "
                                      "now?"},
     {"role": "user", "content": "Get home at 6, cook, help with homework, laundry, then I scroll on my phone until "
                                 "midnight."}],
]


def household_prompts() -> list[dict]:
    items: list[dict] = []
    for kind, pre, lst in (("chat", "hchat", HCHAT), ("prose", "hprose", HPROSE), ("advice", "hadvice", HADVICE)):
        for j, text in enumerate(lst):
            assert text not in EXCLUDED
            sysmsg = SYSTEMS[(j + 1) % len(SYSTEMS)]
            msgs = ([{"role": "system", "content": sysmsg}] if sysmsg else []) + [{"role": "user", "content": text}]
            items.append({"id": f"{pre}-{j:03d}", "kind": kind, "messages": msgs})
    for j, dialog in enumerate(HDIALOGS):
        items.append({"id": f"hdlg-{j:03d}", "kind": "chat", "messages": dialog})
    return items
