#!/usr/bin/env python3
"""Record self-distillation data for a Flash Next MTP head (workstream D), in-process, one GPU job (under the lock).
Any checkpoint the TensorFold tree loads (MLX 4-bit, NVFP4 ModelOpt, EXL3): the capture runs through the engine's own
forward and MTP code (every row read out), so hidden states and targets are that checkpoint's.

usage: record.py <data_dir> <minutes> --model <dir> [--units N] [--timing] [--only gen|retf] [--plan full|probe]

Work units, in order (each is skipped once <data_dir>/units/<uid>.json exists):
  1. bench: the decode suite's 6 prompts, greedy + seeds 1234-1236, 384 tokens, generated by hibrid48 (never trained on);
  2. eval: the v1 eval-split prompts (data/v1), each mode, generated by hibrid48 (held out);
  3. retf: every v1 train unit's token sequence (the MLX model's replies, data/v1) teacher-forced through hibrid48:
     inputs and targets are hibrid48's own streams and distributions, the text is the MLX model's (fast: no decode);
  4. extra: the prompts file's extra chat/prose/advice prompts (household.py), greedy-off and two sampled-off seeds,
     generated by hibrid48, split 90/10 by prompt id like v1;
  5. gen: the v1 train prompts generated by hibrid48 (on-policy train data, if time allows).
--plan probe: 12 bench, 12 held-out household and 80 retf units (the acceptance probe, ~10 GPU minutes).
A generated unit decodes the reply MTP-drafted (drafted == serial) with the checkpoint's own head; every unit is then
teacher-forced in prompt-sized chunks, recording per position: the streams before the final mixer (bf16 [4 x 2560]),
the top-64 logits (fp32) and ids, the full-vocab log-sum-exp, and the checkpoint MTP head's (CUDA) first-draft
argmax over the draft vocabulary and its probability. Positions past MAXREC are not recorded (training reads 2048).
Model replies are stored as token ids and text only; nothing they contain is executed.
"""
from __future__ import annotations

import argparse
import json
import os
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
from tokenizers import Tokenizer

sys.path.insert(0, str(Path(__file__).resolve().parent))
import household as HH  # noqa: E402
import prompts_v1 as P  # noqa: E402

from tensorfold.engine.exact_sampling import Sampling  # noqa: E402
from tensorfold.families.qwen4_exp.cuda import decode as D  # noqa: E402
from tensorfold.families.qwen4_exp.cuda.engine import FlashNextEngine  # noqa: E402
from tensorfold.families.qwen4_exp.cuda.forward import (_embed, _mm, _readout, _writeback, commit,  # noqa: E402
                                                        layer_forward, stage)
from tensorfold.families.qwen4_exp.cuda import glue  # noqa: E402
from tensorfold.families.qwen4_exp.cuda.mtp import mtp_stage  # noqa: E402

V1 = Path("data/v1")
TOPK = 64
MAXREC = 2048 + 8
HEAD_ROWS = 512
BENCH = P.BENCH  # the speed suite's prompts (``bench`` in the prompts file): recorded for evaluation only


def work_units(plan: str = "full") -> list[dict]:
    bench = []
    for pid, text in BENCH.items():
        item = {"id": pid, "kind": pid.split("-")[1], "messages": [{"role": "user", "content": text}]}
        for mode, seed in (("greedy-off", 0), ("sampled-off", 1234), ("sampled-off", 1235), ("sampled-off", 1236)):
            bench.append({"uid": f"{pid}--{mode}-{seed}", "pid": pid, "kind": item["kind"], "split": "bench",
                          "mode": mode, "seed": seed, "item": item, "src": "gen"})
    v1_eval, v1_gen = [], []
    for i, item in enumerate(P.all_prompts()):
        split = P.split(item["id"])
        for mode in ("greedy-off", "sampled-off", "greedy-on" if i % 2 else "sampled-on"):
            u = {"uid": f"{item['id']}--{mode}", "pid": item["id"], "kind": item["kind"], "split": split,
                 "mode": mode, "seed": 1000 + i, "item": item, "src": "gen"}
            (v1_eval if split == "eval" else v1_gen).append(u)
    retf = []
    for f in sorted((V1 / "units").glob("*.json")):
        meta = json.loads(f.read_text())
        if meta["split"] == "train":
            retf.append({"uid": "retf--" + meta["uid"], "pid": meta["pid"], "kind": meta["kind"], "split": "train",
                         "mode": meta["mode"], "seed": meta["seed"], "src": "retf", "v1": str(f.with_suffix(".npz")),
                         "prompt_len": meta["prompt_len"]})
    house = []
    for i, item in enumerate(HH.household_prompts()):
        split = P.split(item["id"])
        for mode, seed in (("greedy-off", 0), ("sampled-off", 5000 + i), ("sampled-off", 7000 + i)):
            house.append({"uid": f"{item['id']}--{mode}-{seed}", "pid": item["id"], "kind": item["kind"],
                          "split": split, "mode": mode, "seed": seed, "item": item, "src": "gen"})
    rng = random.Random(1)
    rng.shuffle(v1_eval)
    rng.shuffle(retf)
    rng.shuffle(house)
    rng.shuffle(v1_gen)
    for u in v1_gen:
        u["uid"] = "gen--" + u["uid"]
    # the household kinds' held-out units first: the early acceptance check (kill-early gate) needs them
    early = [u for u in v1_eval if u["kind"] in ("prose", "chat", "advice")]
    late = [u for u in v1_eval if u["kind"] not in ("prose", "chat", "advice")]
    if plan == "house":                      # on-policy household replies: one sampled reply a prompt, held-out first
        hs = [u for u in house if u["mode"] == "sampled-off" and u["seed"] < 7000]
        return [u for u in hs if u["split"] == "eval"] + [u for u in hs if u["split"] == "train"]
    if plan == "probe":                      # ~10 GPU minutes with the load: 12 bench + 12 held-out household + 80 retf
        hh = [u for u in house if u["split"] == "eval" and u["mode"].startswith("sampled")]
        return [u for u in bench if u["seed"] in (0, 1234)] + early[:4] + hh[:8] + retf[:80]
    return bench + early + retf + late + house + v1_gen


def finish_all(w, mixer, b, R, pending) -> None:
    """``forward.finish`` for every row of a prompt-chunk buffer (the prompt path reads out only its last row)."""

    c = w.cfg
    b.streams[:R].copy_(b.h[:R])
    _writeback(b.streams, b, R, c, pending)
    _readout(mixer, b, b.streams, R, c.eps, c.streams, c.low, None)


def forward_all(w, st, b, tokens) -> int:
    """The main model over a chunk (rows at st.pos ..): b.streams[:R] and the mixer's b.mixed[:R] for every row."""

    segs = stage(w, b, [(st, tokens)])
    R = segs[-1][2]
    _embed(w, b.ids[:R], w.cfg.streams, b.h[:R])
    pending = None
    for layer in w.layers:
        pending = layer_forward(layer, w, segs, b, R, pending)
    finish_all(w, w.mixer, b, R, pending)
    return R


def mtp_all(w, st, b, next_tokens, streams) -> int:
    """The MTP head over a chunk (``mtp.mtp_compute``, every row read out): b.mixed[:n]; the caller advances mtp_len."""

    c, m = w.cfg, w.mtp
    segs = mtp_stage(w, b, [(st, next_tokens, streams)])
    n = segs[-1][2]
    _embed(w, b.ids[:n], 1, b.mtp_e[:n])
    en, xe = glue.rmsnorm(b.mtp_e[:n], m.norm_e, c.eps, out=b.mixed[:n], xs=b.xs_mixed[:n])
    _mm(en, m.fc_e, xe, b.mtp_eo[:n], b)
    hn, xh = glue.rmsnorm(b.mtp_in[:n], m.norm_h, c.eps, out=b.mtp_hn[:n], xs=b.mtp_xh[:n])
    _mm(hn.view(n * c.streams, c.hidden), m.fc_h, xh.view(n * c.streams, c.hidden // 32), b.mtp_hs[:n * c.streams], b)
    glue.add_streams(b.mtp_eo[:n], b.mtp_hs[:n * c.streams], b.h[:n], c.streams)
    pending = layer_forward(m.layer, w, segs, b, n, None, mtp=True)
    finish_all(w, m.mixer, b, n, pending)
    return n


def heads(w, b, R, head, out) -> torch.Tensor:
    """Rows b.mixed[:R] through a head in chunks of HEAD_ROWS: fp32 logits chunks are yielded to the caller."""

    for r0 in range(0, R, HEAD_ROWS):
        r1 = min(R, r0 + HEAD_ROWS)
        o = _mm(b.mixed[r0:r1], head, b.xs_mixed[r0:r1], out[:r1 - r0], b)
        yield r0, r1, o


def teacher_force(e, seq: list[int], row0: int = 0) -> dict:
    """Teacher-force ``seq`` from its start; record rows row0 .. row0 + MAXREC - 1 (a long trace keeps its last rows)."""

    w, st, pb = e.w, e.st, e.pbuf
    end = min(len(seq), row0 + MAXREC)
    N = end - row0
    streams = np.empty((N, w.cfg.streams * w.cfg.hidden), dtype=np.uint16)
    top_v = np.empty((N, TOPK), dtype=np.float32)
    top_i = np.empty((N, TOPK), dtype=np.int32)
    lse = np.empty((N,), dtype=np.float32)
    m_top = np.full((N,), -1, dtype=np.int32)
    m_p = np.zeros((N,), dtype=np.float32)
    out = torch.empty((HEAD_ROWS, w.head.n), dtype=torch.bfloat16, device="cuda")
    dout = torch.empty((HEAD_ROWS, w.draft_head.n), dtype=torch.bfloat16, device="cuda")
    draft_ids = w.draft_ids
    e.reset()
    for s0 in range(0, end, e.prefill_rows):
        chunk = seq[s0:min(end, s0 + e.prefill_rows)]
        R = forward_all(w, st, pb, chunk)
        keep0 = max(0, row0 - s0)                     # first row of this chunk to record
        if keep0 < R:
            a = s0 + keep0 - row0
            for r0, r1, lg in heads(w, pb, R, w.head, out):
                if r1 <= keep0:
                    continue
                q0 = max(r0, keep0)
                lf = lg[q0 - r0:].float()
                v, i_ = torch.topk(lf, TOPK, dim=-1)
                top_v[s0 + q0 - row0:s0 + r1 - row0] = v.cpu().numpy()
                top_i[s0 + q0 - row0:s0 + r1 - row0] = i_.to(torch.int32).cpu().numpy()
                lse[s0 + q0 - row0:s0 + r1 - row0] = torch.logsumexp(lf, dim=-1).cpu().numpy()
            streams[a:s0 + R - row0] = pb.streams[keep0:R].contiguous().view(torch.int16).cpu().numpy().view(np.uint16)
        nxt = seq[s0 + 1:s0 + R + 1]
        if nxt:
            n = mtp_all(w, st, pb, nxt, pb.streams[:len(nxt)])
            if keep0 < n:
                for r0, r1, lg in heads(w, pb, n, w.draft_head, dout):
                    if r1 <= keep0:
                        continue
                    q0 = max(r0, keep0)
                    pm, am = torch.softmax(lg[q0 - r0:].float(), dim=-1).max(dim=-1)
                    m_top[s0 + q0 - row0:s0 + r1 - row0] = draft_ids[am].to(torch.int32).cpu().numpy()
                    m_p[s0 + q0 - row0:s0 + r1 - row0] = pm.cpu().numpy()
            st.set_mtp_len(st.mtp_len + n)
        commit(w, st, pb, R, R)
    torch.cuda.synchronize()
    return dict(tokens=np.array(seq[row0:end], dtype=np.int32), streams=streams, top_v=top_v, top_i=top_i, lse=lse,
                mtp_top=m_top, mtp_p=m_p)


def timing(e, tok, out: Path) -> None:  # noqa: C901
    """Verify windows of 1..max_rows rows and one MTP draft step, eager as hibrid48 decodes (ms, median of 7), at a short
    context after a real prompt; the cost rule's inputs (decode.VERIFY_MS / DRAFT_MS) for hibrid48."""

    ids = tok.encode(P.render({"messages": [{"role": "user", "content": BENCH["bench-chat"]}]}, False)).ids
    first = D.prefill(e, ids, None)
    r = D.mtp_decode(e, first, 64, None)
    toks = r.tokens[-e.rows:]
    res = {}
    for R in range(1, e.rows + 1):
        ts = []
        for _ in range(8):
            torch.cuda.synchronize()
            t0 = time.perf_counter()
            e.forward(toks[:R])
            torch.cuda.synchronize()
            ts.append((time.perf_counter() - t0) * 1000)
        res[R] = float(np.median(ts[1:]))
    ds = []
    for _ in range(8):
        torch.cuda.synchronize()
        t0 = time.perf_counter()
        e.mtp_forward([toks[0]], e.buf.streams[:1])
        torch.cuda.synchronize()
        ds.append((time.perf_counter() - t0) * 1000)
    rec = {"verify_ms": res, "draft_ms": float(np.median(ds[1:])), "context": e.st.pos}
    (out / "timing.json").write_text(json.dumps(rec, indent=1))
    print("timing", rec, flush=True)


def main() -> None:
    global MAXREC
    ap = argparse.ArgumentParser()
    ap.add_argument("data_dir")
    ap.add_argument("minutes", type=float)
    ap.add_argument("--units", type=int, default=0)
    ap.add_argument("--timing", action="store_true")
    ap.add_argument("--only", choices=("gen", "retf"), default=None)
    ap.add_argument("--max-len", type=int, default=8192)
    ap.add_argument("--maxrec", type=int, default=MAXREC, help="rows recorded a unit (long-context sets: lift the cap)")
    ap.add_argument("--model", required=True)
    ap.add_argument("--plan", choices=("full", "probe", "house"), default="full")
    ap.add_argument("--set", default=None, help="a build_set.py file: teacher-force its units only (no decoding)")
    a = ap.parse_args()
    t_start = time.time()
    out = Path(a.data_dir)
    (out / "units").mkdir(parents=True, exist_ok=True)
    done = {p.stem for p in (out / "units").glob("*.json")}
    MAXREC = a.maxrec
    M = Path(a.model)
    (out / "model.txt").write_text(f"{M}\n")
    if a.set:
        units = [json.loads(line) for line in open(a.set)]
        for u in units:
            u["src_set"] = u["src"]
            u["src"] = "set"
    else:
        units = work_units(a.plan)
    todo = [u for u in units if u["uid"] not in done and (a.only is None or u["src"] == a.only)]
    print(f"{len(done)} units done, {len(todo)} to do", flush=True)
    if not todo and not a.timing:
        (out / "COMPLETE").write_text("all units recorded\n")
        return
    tok = Tokenizer.from_file(str(M / "tokenizer.json"))
    fe = FlashNextEngine(M, max_len=a.max_len, context_explicit=True)
    e, w = fe.e, fe.w
    print(f"engine ready in {time.time() - t_start:.0f}s; graphs={e.graphs is not None} depth={fe.depth} "
          f"conf={fe.confidence} cost={fe.cost} prefill_rows={e.prefill_rows} draft_vocab={w.draft_head.n} "
          f"mtp_head={w.meta.get('mtp_head')}", flush=True)
    if a.timing:
        with torch.no_grad():
            timing(e, tok, out)
    budget = a.minutes * 60
    n_done = 0
    for u in todo:
        if time.time() - t_start > budget or (a.units and n_done >= a.units):
            break
        t0 = time.time()
        meta = {k: u[k] for k in ("uid", "pid", "kind", "split", "mode", "seed", "src")}
        with torch.no_grad():
            if u["src"] == "set":
                seq, P0, reply = u["tokens"], int(u["spans"][0][0]), []
                meta["src"] = u["src_set"]
                meta.update(decode_s=None, rounds=None, drafted=None, accepted=None, text=None,
                            spans=u["spans"], row0=u["row0"])
            elif u["src"] == "retf":
                seq = [int(t) for t in np.load(u["v1"])["tokens"]]
                P0 = int(u["prompt_len"])
                reply = seq[P0:]
                meta.update(decode_s=None, rounds=None, drafted=None, accepted=None, text=None)
            else:
                thinking = u["mode"].endswith("-on")
                ids = tok.encode(P.render(u["item"], thinking)).ids
                if len(ids) + 520 > a.max_len:
                    print(f"skip {u['uid']}: prompt {len(ids)}", flush=True)
                    continue
                samp = None if u["mode"].startswith("greedy") else Sampling(seed=u["seed"], temperature=0.7,
                                                                              top_k=20, top_p=0.8)
                n_reply = 256 + (sum(map(ord, u["uid"])) * 7919) % 257 if u["split"] != "bench" else 384
                if a.plan == "house":
                    n_reply = 256 + (sum(map(ord, u["uid"])) * 7919) % 65
                first = D.prefill(e, ids, samp)
                r = D.mtp_decode(e, first, n_reply, samp, stop_eos=True, depth=fe.depth, confidence=fe.confidence,
                                 cost=fe.cost)
                reply = list(r.tokens)
                seq = ids + reply
                P0 = len(ids)
                meta.update(decode_s=round(r.seconds, 3), rounds=r.rounds, drafted=r.drafted, accepted=r.accepted,
                            keeps=r.keeps, text=tok.decode(reply, skip_special_tokens=False))
            row0 = int(u.get("row0", 0)) if u["src"] == "set" else 0
            rec = teacher_force(e, seq, row0)
        N = len(rec["tokens"])
        if u["src"] == "set":                         # window-relative: rows are seq[row0:]
            P0 = max(0, P0 - row0)
            seq = seq[row0:]
        greedy_match = None
        if u["mode"].startswith("greedy") and u["src"] == "gen":
            # the teacher-forced argmax must be the greedy reply (drafted == serial == teacher-forced, up to ties)
            greedy_match = float(np.mean(rec["top_i"][P0 - 1:N - 1, 0] == np.array(seq[P0:N])))
        top1_text = (float(np.mean(rec["top_i"][max(P0, 1) - 1:N - 1, 0] == np.array(seq[max(P0, 1):N])))
                     if N > max(P0, 1) else None)
        np.savez(out / "units" / f"{u['uid']}.npz", **rec)
        meta.update(prompt_len=P0, n=N, n_full=len(seq) + (row0 if u["src"] == "set" else 0), reply_len=len(reply), greedy_match=greedy_match,
                    top1_text=top1_text, record_s=round(time.time() - t0, 2))
        (out / "units" / f"{u['uid']}.json").write_text(json.dumps(meta))
        n_done += 1
        tps = "" if meta["decode_s"] is None else f"tps={(len(reply) - 1) / max(meta['decode_s'], 1e-9):.1f} " \
                                                  f"acc={meta['accepted']}/{meta['drafted']} rounds={meta['rounds']} "
        print(f"{u['uid']} P={P0} N={N} {tps}greedy_match={greedy_match} top1_text={top1_text} "
              f"{time.time() - t0:.1f}s", flush=True)
    left = len([u for u in todo]) - n_done
    print(f"recorded {n_done} units this job; {left} left; {time.time() - t_start:.0f}s", flush=True)
    if left <= 0:
        (out / "COMPLETE").write_text("all units recorded\n")


if __name__ == "__main__":
    main()
